### ISSUE TITLE
Implement http layer

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/conda-adapter#32]
Let's implement http layer in the adapter and integrate adapter to artpie ecosystem.

Before closing this ticket make sure all test coverages ratios are not lower than 0.75, missed test classes count is not lover than 4.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#37](https://github.com/artipie/conda-adapter/issues/37) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova 5 puzzles [#37](https://github.com/artipie/conda-adapter/issues/37), [#39](https://github.com/artipie/conda-adapter/issues/39), [#40](https://github.com/artipie/conda-adapter/issues/40), [#41](https://github.com/artipie/conda-adapter/issues/41), [#42](https://github.com/artipie/conda-adapter/issues/42) are still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova 6 puzzles [#37](https://github.com/artipie/conda-adapter/issues/37), [#39](https://github.com/artipie/conda-adapter/issues/39), [#40](https://github.com/artipie/conda-adapter/issues/40), [#41](https://github.com/artipie/conda-adapter/issues/41), [#42](https://github.com/artipie/conda-adapter/issues/42), [#51](https://github.com/artipie/conda-adapter/issues/51) are still not solved.

**Comment by olenagerasimova** [comment]
done

**Comment by 0pdd** [comment]
@olenagerasimova 6 puzzles [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.
